### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by peter-hunt** [pjpuzzler/cpp-chess#1]
I used the python-chess project, and because of how slow python is compared to c++, I was thinking about the same thing!
I'm not familiar with c++ but I wanted to build a fast chess engine, and this project is exactly as I needed it.
Thank you for building this repo!

**Comment by pjpuzzler** [comment]
Glad you enjoy it!

**Comment by tissatussa** [comment]
@peter-hunt did you build that fast chess engine yet ? On your GitHub page i don't see such code ..
